development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:3a5ba5c8a40f362c1bff15244ae23a1c@crestfish.redistogo.com:10679/
  channel_prefix: earbuddies_production
