# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

Event.destroy_all

# 10.times do |index|
#   Event.create!(date: Faker::Time,
#                 venue_id: Faker::Number,
#                 ticket_url: Faker::Internet.url,
#                 image: Faker::Internet.url,
#                 )
# end




e11 = Event.create :name => 'Oasis', :description => 'Oasis were an English rock band formed in Manchester in 1991. Developed from an earlier group, the Rain, the band originally consisted of Liam Gallagher (vocals, tambourine), Paul "Bonehead" Arthurs (guitar), Paul "Guigsy" McGuigan (bass guitar), and Tony McCarroll (drums). Upon returning to Manchester, Liam\'s older brother, Noel Gallagher (lead guitar, vocals) was asked to join as a fifth member, becoming the band\'s core and settled line-up. During the course of their existence, they have undergone various line-up changes. As well as singing in Mancunian accents and references to British culture in their lyrics, Oasis were influenced by British guitar bands from the past.' , :date=> Faker::Time, :venue_id=> 'Hordern Pavillion', :ticket_url => Faker::Internet.url, :genre => 'Rock', :image => 'https://upload.wikimedia.org/wikipedia/commons/7/73/Oasis_Liam_and_Noel.jpg'
e12 = Event.create :name => 'Cloud Control', :description => 'Cloud Control is an Australian alternative rock band, originating from the Blue Mountains near Sydney, Australia.[1] As of 2013 the band is signed to the Australian record label Ivy League Records, in which they released their debut album Bliss Release. They are also signed to Infectious Music in the UK/Europe; and Votiv in North America.', :date=> Faker::Time, :venue_id=> 'Oxford Art Factory', :ticket_url => Faker::Internet.url, :genre => 'Alternative', :image => 'https://upload.wikimedia.org/wikipedia/commons/8/86/Cloud_control.jpg'
e13 = Event.create :name => 'Fleet Foxes', :description => 'Fleet Foxes is an American indie folk band formed in Seattle, Washington.[5] Their first two albums were released by the Sub Pop and Bella Union record labels, with their third by Nonesuch and Bella Union. The band came to prominence in 2008 with the release of their second EP, Sun Giant, and their self-titled debut album. Both received much critical praise and reviewers often noted the band\'s use of refined lyrics and vocal harmonies. Fleet Foxes\' second studio album, Helplessness Blues, was released on May 3, 2011, and their third album, Crack-Up, was released on June 16, 2017, on Nonesuch Records.' , :date=> Faker::Time, :venue_id=> 'Sydney Opera House', :ticket_url => Faker::Internet.url, :genre => 'Folk Rock', :image => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Fleetfoxes08.jpg/1280px-Fleetfoxes08.jpg'
e14 = Event.create :name => 'El-P', :description => 'Jaime Meline, better known by his stage name El-P (shortened from El Producto), is an American rapper, record producer, and record executive. Originally a member of Company Flow, El-P has been a major driving force in alternative hip hop for more than two decades, producing for several notable rappers such as Aesop Rock, Mr. Lif, and Cage, among others.' , :date=> Faker::Time, :venue_id=> 'Enmore Theatre', :ticket_url => Faker::Internet.url, :genre => 'Rap', :image => 'https://hitberry.com/uploads/2015/12/rapper-el-p-and-girlfriend-emily-panic-getting-married.jpg'
e15 = Event.create :name => 'Justin Bieber', :description => 'Justin Drew Bieber is a Canadian singer and songwriter. After a talent manager discovered him through his YouTube videos covering songs in 2008 and he signed to RBMG, Bieber released his debut EP, My World, in late 2009. It was certified platinum in the U.S. He became the first artist to have seven songs from a debut record chart on the Billboard Hot 100. Bieber released his first full-length studio album, My World 2.0, in 2010. It debuted at or near number one in several countries, was certified triple platinum in the U.S., and contained his single "Baby".' , :date=> Faker::Time, :venue_id=> 'Qudos Bank Arena', :ticket_url => Faker::Internet.url, :genre => 'Pop', :image => 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Justin_Bieber_Miami_Beach_Police_Department_March_04%2C_2014.jpg'
e16 = Event.create :name => 'Sonic Youth', :description => 'A reunion tour for Sonic Youth, the American rock band based in New York City, formed in 1981. Founding members Thurston Moore (guitar, vocals), Kim Gordon (bass, vocals, guitar) and Lee Ranaldo (guitar, vocals) remained together for the entire history of the band, while Steve Shelley (drums) followed a series of short-term drummers in 1985, and rounded out the core line-up.' , :date=> Faker::Time, :venue_id=> 'The Metro Theatre', :ticket_url => Faker::Internet.url, :genre => 'Punk', :image => 'https://static.guim.co.uk/sys-images/Admin/BkFill/Default_image_group/2011/10/16/1318769205783/Sonic-Youth-007.jpg'
e17 = Event.create :name => 'Blink-182', :description => 'Blink-182 is an American rock band formed in Poway, California in 1992. Since 2015, the lineup of the band has consisted of bassist and vocalist Mark Hoppus, drummer Travis Barker, and guitarist and vocalist Matt Skiba. Founded by guitarist and vocalist Tom DeLonge, Hoppus and drummer Scott Raynor, the band emerged from the Southern California punk scene of the early 1990s and first gained notoriety for high-energy live shows and irreverent lyrical toilet humor. Blink-182 was initially known as Blink until an Irish band of the same name threatened legal action; in response, the band appended the meaningless number "-182".', :date=> Faker::Time, :venue_id=> 'The Metro Theatre', :ticket_url => Faker::Internet.url, :genre => 'Pop-Punk', :image => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Blink182.jpg/1024px-Blink182.jpg'
e18 = Event.create :name => 'Jeremih', :description => Faker::Simpsons.quote , :date=> Faker::Time, :venue_id=> 'Oxford Art Factory', :ticket_url => Faker::Internet.url, :genre => 'Rap', :image => Faker::Internet.url
e19 = Event.create :name => 'Foo Fighters', :description => 'Foo Fighters is an American rock band, formed in Seattle, Washington in 1994. It was founded by Nirvana drummer Dave Grohl as a one-man project following the dissolution of Nirvana after the death of Kurt Cobain. The group got its name from the UFOs and various aerial phenomena that were reported by Allied aircraft pilots in World War II, which were known collectively as "foo fighters".' , :date=> Faker::Time, :venue_id=> 'Enmore Theatre', :ticket_url => Faker::Internet.url, :genre => 'Rock', :image => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/FoosLollBerlin190917-74_%28cropped%29.jpg/1024px-FoosLollBerlin190917-74_%28cropped%29.jpg'
e20 = Event.create :name => 'Foals', :description => 'Foals are a rock band from Oxford, England formed in 2005, consisting of lead vocalist and lead guitarist Yannis Philippakis, drummer and percussionist Jack Bevan, rhythm guitarist Jimmy Smith, and keyboardist Edwin Congreave. They are currently signed to Warner Bros. Records,[1] and have released four studio albums: Antidotes (2008), Total Life Forever (2010), Holy Fire (2013), What Went Down (2015), one video album, six extended plays and nineteen singles.' , :date=> Faker::Time, :venue_id=> 'Enmore Theatre', :ticket_url => Faker::Internet.url, :genre => 'Progressive Rock', :image => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Foals_-_Roskilde_Festival_2011_-_Arena_Stage.jpg/1280px-Foals_-_Roskilde_Festival_2011_-_Arena_Stage.jpg'
e21 = Event.create :name => 'Arca', :description => 'Alejandro Ghersi (born October 14, 1989), better known by his stage name Arca, is a Venezuelan electronic music producer, songwriter, mixing engineer and DJ based in Dalston, London.[5][6][7] He has released three studio albums to critical praise and has produced for artists such as Björk, Kanye West, FKA twigs, Kelela and Frank Ocean.' , :date=> Faker::Time, :venue_id=> 'Sydney Opera House', :ticket_url => Faker::Internet.url, :genre => 'Electronic', :image => 'http://dazedimg.dazedgroup.netdna-cdn.com/1400/azure/dazed-prod/1100/1/1101602.jpg'
e22 = Event.create :name => 'Kavinsky', :description => 'Vincent Belorgey[2] (born July 31, 1975), known as Kavinsky (formerly stylized as ꞰΛVINϟKY), is a French house[3][4] artist whose production style is very reminiscent of the electropop film soundtracks of the 1980s.[5] Kavinsky claimed that his music is inspired by thousands of movies he watched as a young boy and that he has cherry-picked the best parts from them, consolidating them into one concept.[6] Kavinsky has been compared to many similar French house artists including Daft Punk and Danger. He achieved greater mainstream recognition after his track "Nightcall" was featured in the 2011 film Drive.' , :date=> Faker::Time, :venue_id=> 'Hordern Pavillion', :ticket_url => Faker::Internet.url, :genre => 'Synth-wave', :image => 'https://f4.bcbits.com/img/0002750941_10.jpg'
e23 = Event.create :name => 'Pearl Jam', :description => 'Pearl Jam is an American rock band formed in Seattle, Washington, in 1990. Since its inception, the band\'s line-up has consisted of Eddie Vedder (lead vocals), Mike McCready (lead guitar), Stone Gossard (rhythm guitar) and Jeff Ament (bass). The band\'s fifth member is drummer Matt Cameron (also of Soundgarden), who has been with the band since 1998. Boom Gaspar (piano) has also been a session/touring member with the band since 2002. Drummers Dave Krusen, Matt Chamberlain, Dave Abbruzzese and Jack Irons are former members of the band.', :date=> Faker::Time, :venue_id=> 'The Metro Theatre', :ticket_url => Faker::Internet.url, :genre => 'Rock', :image => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/PJ_2012.jpg/1920px-PJ_2012.jpg'
e24 = Event.create :name => 'Big Boi', :description => 'Antwan André Patton, better known by his stage name Big Boi, is an American rapper, songwriter, actor and record producer, best known for being a member of American hip hop duo Outkast alongside André 3000. His work in the duo has produced six studio albums. Big Boi\'s solo debut Sir Lucious Left Foot: The Son of Chico Dusty was released in July 2010 to respectable sales and critical acclaim. He released his second studio album, Vicious Lies and Dangerous Rumors in 2012. Boomiverse, his third studio album, was released in June 2017.' , :date=> Faker::Time, :venue_id=> 'The Metro Theatre', :ticket_url => Faker::Internet.url, :genre => 'Rap', :image => 'https://upload.wikimedia.org/wikipedia/commons/4/42/Big_Boi_Counterpoint.jpg'
e25 = Event.create :name => 'Alt-J', :description => 'Alt-J is an English indie rock band formed in 2007 in Leeds, by Joe Newman (guitar/lead vocals), Thom Sonny Green (drums), Gus Unger-Hamilton (keyboards/vocals) and Gwil Sainsbury (guitar/bass). The band\'s debut album An Awesome Wave was released in May 2012 in Europe, and in September 2012 in the United States, and won the 2012 British Mercury Prize. Gwil Sainsbury amicably departed the band in early 2014. Their second album, This Is All Yours, was released on 22 September 2014 and went straight to UK number one. As a replacement for Sainsbury, Cameron Knight became a supporting member for alt-J\'s live shows, playing guitar, bass and sampler. In 2017, the band released their third studio album, Relaxer, and are currently playing as a trio.', :date=> Faker::Time, :venue_id=> 'The State Theatre', :ticket_url => Faker::Internet.url, :genre => 'Alternative', :image => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Alt-J_Fall_Tour_2015_live_in_Charlotte.jpg/1024px-Alt-J_Fall_Tour_2015_live_in_Charlotte.jpg'
e26 = Event.create :name => 'The Raincoats', :description => 'The Raincoats are a British post-punk and experimental rock band. Ana da Silva (vocals, guitar) and Gina Birch (vocals, bass) formed the group in 1977 while they were students at Hornsey College of Art in London, England.' , :date=> Faker::Time, :venue_id=> 'The State Theatre', :ticket_url => Faker::Internet.url, :genre => 'Alternative', :image => 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Raincoats.jpg'
e27 = Event.create :name => 'The Decemberists', :description => 'The Decemberists are an American indie rock band from Portland, Oregon. The band consists of Colin Meloy (lead vocals, guitar, principal songwriter), Chris Funk (guitar, multi-instrumentalist), Jenny Conlee (piano, keyboards), Nate Query (bass), and John Moen (drums).

Their debut EP, 5 Songs, was self-released in 2001. Their eighth and latest full-length album I\'ll Be Your Girl was released on March 16, 2018 by Capitol Records, and is the band\'s fifth record with the label.' , :date=> Faker::Time, :venue_id=> 'Sydney Opera House', :ticket_url => Faker::Internet.url, :genre => 'Folk-Rock', :image => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/The_Decemberists_live_in_Vienna.jpg/1024px-The_Decemberists_live_in_Vienna.jpg'
e28 = Event.create :name => 'Mumford & Sons', :description => 'Mumford & Sons are a British band formed in 2007. The band consists of Marcus Mumford (lead vocals, electric guitar, acoustic guitar, drums), Ben Lovett (vocals, keyboard, piano, synthesizer), Winston Marshall (vocals, electric guitar, banjo) and Ted Dwane (vocals, bass guitar, double bass).' , :date=> Faker::Time, :venue_id=> 'Qudos Bank Arena', :ticket_url => Faker::Internet.url, :genre => 'Folk-Rock', :image => Faker::Internet.url
e29 = Event.create :name => 'Chvrches', :description => Faker::Simpsons.quote , :date=> Faker::Time, :venue_id=> 'Hordern Pavillion', :ticket_url => Faker::Internet.url, :genre => 'Pop', :image => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/MS2015.jpg/1920px-MS2015.jpg'
e30 = Event.create :name => 'Slipknot', :description => 'Slipknot is well known for its attention-grabbing image, aggressive style of music, and energetic and chaotic live shows.[1][2] The band rapidly rose to success following the release of their eponymous debut album in 1999. The 2001 follow-up album, Iowa, although darker in tone, made the band more popular. After a brief hiatus, Slipknot returned in 2004 with Vol. 3: (The Subliminal Verses), before going on another hiatus and returning in 2008 with its fourth album, All Hope Is Gone, which debuted at number one on the Billboard 200 chart. After another long hiatus, Slipknot released its fifth studio album, .5: The Gray Chapter, in 2014.' , :date=> Faker::Time, :venue_id=> 'Enmore Theatre', :ticket_url => Faker::Internet.url, :genre => 'Metal', :image => 'http://cdn1-www.musicfeeds.com.au/assets/uploads/476c2a539bfeed74a86aafd4086fce2d.jpg'
e31 = Event.create :name => 'Animal Collective', :description => 'Animal Collective is an American experimental pop band formed in Baltimore, Maryland in 2003. Its members and founders are Avey Tare (David Portner), Panda Bear (Noah Lennox), Deakin (Josh Dibb), and Geologist (Brian Weitz). The band\'s music is characterized by studio experimentation, vocal harmonies, and an exploration of various genres which include freak folk, noise rock, ambient drone, and psychedelia. Records released under the name "Animal Collective" may include contributions from any or all of its members. In the case of Dibb, who often takes breaks from recording and performing with the band, his time off does not constitute full leave.' , :date=> Faker::Time, :venue_id=> 'Qudos Bank Arena', :ticket_url => Faker::Internet.url, :genre => 'Electronic', :image => 'https://media.npr.org/assets/img/2016/02/11/animal_collective_-__photo_credit_tom_andrew_-ac3-__300pi_wide-97276b46108636c98119d4940f451bca4a735cdd-s800-c85.jpg'
e32 = Event.create :name => 'GWAR', :description => 'Easily identified by their distinctively grotesque costumes, Gwar\'s core thematic and visual concept revolves around an elaborate science fiction-themed mythology which portrays the band members as barbaric interplanetary warriors, a narrative which serves as the basis for all of the band\'s albums, videos, live shows and other media. Rife with over-the-top violent, sexual, and scatological humour typically incorporating social and political satire, Gwar have attracted both acclaim and controversy for their music and stage shows, the latter of which notoriously showcase enactments of graphic violence that result in the audience being sprayed with copious amounts of fake blood, urine, and semen. Such stagecraft regularly leads Gwar to be labeled a "shock rock" band by the media.' , :date=> Faker::Time, :venue_id=> 'Enmore Theatre', :ticket_url => Faker::Internet.url, :genre => 'Metal', :image => 'http://www.socold.org/wp-content/uploads/2017/06/Gwar-Characters.jpg'

Venue.destroy_all
v1 = Venue.create :location => Faker::Address.latitude, :name => 'Hordern Pavillion', :url => Faker::Internet.url, :address => '1 Driver Ave, Moore Park NSW 2021'
v2 = Venue.create :location => Faker::Address.latitude, :name => 'Oxford Art Factory', :url => Faker::Internet.url, :address => '38-46 Oxford St, Darlinghurst NSW 2010'
v3 = Venue.create :location => Faker::Address.latitude, :name => 'Sydney Opera House', :url => Faker::Internet.url, :address => 'Bennelong Point, Sydney NSW 2000'
v4 = Venue.create :location => Faker::Address.latitude, :name => 'Enmore Theatre', :url => Faker::Internet.url, :address => '118-132 Enmore Rd, Newtown NSW 2042'
v5 = Venue.create :location => Faker::Address.latitude, :name => 'Qudos Bank Arena', :url => Faker::Internet.url, :address => 'Edwin Flack Ave & Olympic Blvd, Sydney Olympic Park NSW 2127'
v6 = Venue.create :location => Faker::Address.latitude, :name => 'The Metro Theatre', :url => Faker::Internet.url, :address => '624 George St, Sydney NSW 2000'
v7 = Venue.create :location => Faker::Address.latitude, :name => 'The State Theatre', :url => Faker::Internet.url, :address => '49 Market St, Sydney NSW 2000'


# User.destroy_all
# 10.times do |index|
#   User.create!(name: Faker::Time,
#                 image: Faker::Number,
#                 bio: Faker::Internet.url,
#                 hometown: Faker::Address.city,
#                 interests: Faker::Job.title,
#                 email: Faker::Internet.email,
#                 )
# end

#Venue and Events
v1.events << e11 << e22 << e29
v2.events << e12 << e18
v3.events << e13 << e21 << e27
v4.events << e14 << e19 << e20 << e30
v5.events << e15 << e28 << e31
v6.events << e16 << e17 << e23 << e24
v7.events << e25 << e26
